### ISSUE TITLE
Closes widgets via X isn't registered as unticking in the plugin menu

### ISSUE THREAD

**Issue by ruaridhg** [matplotlib/napari-matplotlib#124]
Workflow:
- Plugins menu --> select widget e.g. Histogram (tick appears next to Histogram and widget appears)
- Close the Histogram widget using the X in the top left corner of the widget so it disappears
- Plugins menu Histogram widget still has a tick next to it and clicking Histogram again makes the tick disappear and the widget appear so the functionality is swapped

**Comment by dstansby** [comment]
Ha, that shouldn't happen! I tried this with another napari plugin, and it does the same thing, so this isn't just a `napari-matplotlib` issue. Could you report this upstream at https://github.com/Napari/napari, and post a link here?

**Comment by dstansby** [comment]
Thanks for reporting this upstream - since there's nothing we can do here I'm going to close this issue.
