### ISSUE TITLE
Fix features_scatter_widget unpredictable behaviour

### ISSUE THREAD

**Issue by ruaridhg** [matplotlib/napari-matplotlib#129]
In test_scatter, ScatterWidget was tested by adding 2 images layers and `viewer.layer.selection.add(viewer.layers[ind]` to select both images which appears to work as expected.

FeaturesScatterWidget was tested by adding an image, a labels and a points layers. The labels and a points layer both have associated features.
It is possible to plot feature_1 vs feature_0 for the points layer. However, both the labels and the points layer need to be selected for this to work, otherwise a blank figure is returned.
 
Another odd feature is that when adding the selection of the points and the label layers, the order is inconsistent and the FeaturesScatterWidget only recognises the first layer. 

So it appears that a 2nd layer needs to be selected (even if it's not used) so a blank figure is not returned and the FeaturesScatter plot only uses features in the 1st selected layer.

**Comment by ruaridhg** [comment]
Issues mentioned in the initial description are mainly fixed:

- [X] Only 1 image needs to be added without 2nd redundant image layer
- [X] Order consistency between layers

Remaining issue:

- [ ] feature_0 v feature_0 being plotted instead of feature_0 v feature_1

**Comment by dstansby** [comment]
>  feature_0 v feature_0 being plotted instead of feature_0 v feature_1

Good catch, the logic should definitely be updated to at least by default start by plotting two different features instead of the same one when the plugin is loaded.
