### ISSUE TITLE
Push built docs to GitHub pages branch

### ISSUE THREAD

**Issue by dstansby** [matplotlib/napari-matplotlib#164]
In https://github.com/matplotlib/napari-matplotlib/pull/132 the doc build was fixed on GitHub actions, but the built docs aren't uploaded anywhere. To do to fix this issue:

- [x] Upload the built docs to a GitHub pages branch
- [ ] Change any references to readthedocs to the new doc URL

**Comment by samcunliffe** [comment]
Partially reached by #172 (#166) and #173 .
But currently not showing (where it's apparently deployed) at https://matplotlib.org/napari-matplotlib

**Comment by dstansby** [comment]
Just emailed a Matplotlib org admin to see what we can do to fix this.
