### ISSUE TITLE
Add hosted API documentation

### ISSUE THREAD

**Issue by dstansby** [matplotlib/napari-matplotlib#18]
The documentation is currently set up in the `docs` directory, but isn't automatically built or published. This can't be done with readthedocs becuase it's not possible to install `xvfb` there. Instead the docs should be built on GitHub actions and published ot a GitHub pages repository.

**Comment by dstansby** [comment]
I'm having issues with `readthedocs`, specifically getting it to work without x-server erroring after the build. See https://github.com/matplotlib/napari-matplotlib/pull/83 for my attempt.

I think it's better to pivot back to using GitHub pages for this, especially since that's what the [official napari docs](https://github.com/napari/docs) use, so we have an example to follow there and more likeley to have debugging buddies if we do run into any issues.

**Comment by samcunliffe** [comment]
My most recent [example of doing this is in WAZP🐝](https://github.com/SainsburyWellcomeCentre/WAZP/blob/main/.github/workflows/docs_build_and_deploy.yml).

**Comment by dstansby** [comment]
Nice! Maybe a good topic for our in-person dev morning.

**Comment by dstansby** [comment]
I've pivoted back - since the example gallery build doesn't work in GH action either, I figure it's best to disable the gallery build and just use readthedocs for now.
