### ISSUE TITLE
Add a `PropertyWidget` for plotting layer properties

### ISSUE THREAD

**Issue by dstansby** [matplotlib/napari-matplotlib#19]

**Comment by jo-mueller** [comment]
Hi @dstansby ,

thanks for creating this issue. Just to clarify - what should this widget do? Would it be an interface between `layer.properties` and the canvas implementation in this repository? I think the [Table Widget](https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/648ce9c9e7ea1670cd5adb842d486982278ff89b/napari_skimage_regionprops/_table.py#L14) in [napari-skimage-regionprops](https://github.com/haesleinhuepf/napari-skimage-regionprops) could already go a long way here. 

Selecting two columns in a tabular view on measured properties of a layer could then trigger the plotting functions in this repository :)

**Comment by kevinyamauchi** [comment]
Hello @dstansby ! Thanks for the super nice library. I've already learned some things about matplotlib just looking through your code :).

If you're open to the PR, I am about to board a long flight and could make an attempt at a scatter plot and histogram widget that work off of the napari features/properties table.

Initially, I would use the current behavior which selects the data based on the currently selected layer in the napari layer list. In the future, would you be open to offering widgets that allow the selection of the data source to be separate from the selection of the layer from the layer list. I think this is helpful, as some plugins may want to maintain the plotting from one layer while interacting with others.

**Comment by jo-mueller** [comment]
Hey @kevinyamauchi ,

I have also started working on this [here](https://github.com/jo-mueller/napari-matplotlib/tree/visualize-properties-and-features) - feel free to check whether there is something you find useful!

**Comment by kevinyamauchi** [comment]
Thanks, @jo-mueller ! I see that you started adding a table implementation. I didn't add a table in my PR and I think that would be a super useful feature to have as well!

**Comment by jo-mueller** [comment]
The table implement is @haesleinhuepf 's implementation from [napari-skimage-regionprops](https://github.com/haesleinhuepf/napari-skimage-regionprops) - maaaaybe we could eventually move it here - I think it makes more sense to have napari-matplotlib as a dependency of skimage-regionprops than the other way around :)

**Comment by kevinyamauchi** [comment]
Works for me! Thanks for the quick reply @jo-mueller

**Comment by dstansby** [comment]
Fixed by https://github.com/matplotlib/napari-matplotlib/pull/39
