### ISSUE TITLE
HistogramWidget plot title not white in dark theme

### ISSUE THREAD

**Issue by dstansby** [matplotlib/napari-matplotlib#193]
See the title here:
<img width="666" alt="Screenshot 2023-07-26 at 08 46 42" src="https://github.com/matplotlib/napari-matplotlib/assets/6197628/9be621f6-e9d7-4491-8fc2-43bf9775cef9">

**Comment by dstansby** [comment]
I think this is general across all plots

**Comment by K-Meech** [comment]
Just to add that for me all the axis labels are black for the histogram (including numbers on both axes). This is with a new install on Windows via the Napari UI Plugins > Install / Uninstall Plugins...
![Screenshot 2023-11-28 104559](https://github.com/matplotlib/napari-matplotlib/assets/24316371/82cfe23b-906c-4321-9fda-7f114c55481a)

**Comment by Chris-N-K** [comment]
This should be fixed with the merge of #237

**Comment by dstansby** [comment]
Amazing!
