### ISSUE TITLE
Add method for external custom toolbar

### ISSUE THREAD

**Issue by zoccoler** [matplotlib/napari-matplotlib#213]
Hi @dstansby ,

Would you mind considering the idea suggested in this comment?

https://github.com/matplotlib/napari-matplotlib/pull/202#issuecomment-1708833704

That would allow others to replace the toolbar by a customized version.

Looking forward to your reply!

Best,
Marcelo

**Comment by zoccoler** [comment]
Related to this, would there be a way to set the canvas manager like this?

`matplotlib.rcParams["toolbar"] = "toolmanager"`

I think then some code like [in this example](https://github.com/matplotlib/matplotlib/issues/25164#issue-1573171635) would work, but right now I could not make it work (figure.canvas.manager is None)

**Comment by dstansby** [comment]
I think this is beyond scope of napari-matplotlib too, sorry - hopefully you can use the code in https://github.com/matplotlib/napari-matplotlib/pull/214 to achieve the same effect in a third-party library?

**Comment by zoccoler** [comment]
Alright, maybe I will do that then, but for now, I think it will be easier to implement these tools outside the matplotlib toolbar. Thanks for your time!
