### ISSUE TITLE
Figure toolbar has very low contrast with `napari`

### ISSUE THREAD

**Issue by dstansby** [matplotlib/napari-matplotlib#23]
![Screenshot 2022-05-03 at 16 21 54](https://user-images.githubusercontent.com/6197628/166483531-9198f031-413e-4ee8-b387-6526dc88c84b.png)

The toolbar was added in https://github.com/dstansby/napari-matplotlib/pull/21, but has very low constrast as can be seen above. Ideally we should make the buttons white. https://github.com/matplotlib/matplotlib/pull/22607 is a relevant Matplotlib PR where support was added for light buttons in the toolbar.

**Comment by jo-mueller** [comment]
Hi @dstansby ,

We encountered this also in the [napari clusters plotter](https://github.com/BiAPoL/napari-clusters-plotter) and I think @zoccoler knows how to deal with this 👍

**Comment by zoccoler** [comment]
Hi everyone,

Yes, I implemented this part there. I think the result is quite nice looking :)
I can bring it here if that's OK for you.

Best,
Marcelo

**Comment by dstansby** [comment]
Yes please, a PR would be very welcome!
