### ISSUE TITLE
Saving figure has no ticks or axis labels

### ISSUE THREAD

**Issue by Goobley** [matplotlib/napari-matplotlib#231]
I'm building a napari plugin that computes some derived data and plots that in a pane (so we're not directly hooking the plot up to the layer content). I am trying to use the `BaseNapariMPLWidget` to have a single plot with toolbar, rather than just docking the figure canvas. I also want to be able to save the figure, however the none of the the ticks, ticklabels, or axis labels appear in a png of the figure.

<details>
<summary>Minimal example</summary>

```
import matplotlib.pyplot as plt
import napari
import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from napari_matplotlib.base import BaseNapariMPLWidget

if __name__ == '__main__':
    viewer = napari.Viewer()

    complete_widget = BaseNapariMPLWidget(viewer)
    complete_widget.add_single_axes()
    complete_widget.axes.plot(np.arange(10), np.sin(np.arange(10)))
    viewer.window.add_dock_widget(complete_widget, name="Complete")

    figure = plt.figure()
    ax = figure.gca()
    ax.plot(np.arange(10), np.sin(np.arange(10)))
    canvas_widget = FigureCanvasQTAgg(figure)
    viewer.window.add_dock_widget(canvas_widget, name="Canvas")

    complete_widget.figure.savefig("test_napari_mpl.png", dpi=300)
    figure.savefig("test_canvas.png", dpi=300)

    napari.run()
```

</details>

Happy to submit a PR with a bit of guidance as where to start. Is this in the choice of canvas?

**Comment by Goobley** [comment]
Apologies, I realised, whilst adding a screenshot that they are present, but weren't visible against the light mode of my image viewer!

**Comment by samcunliffe** [comment]
Would you mind posting a screenshot? I thought I'd fixed this.

**Comment by Goobley** [comment]
Here we go. Ultimately it stemmed from napari being in dark mode, but my image viewer being in light mode, with the plot having a transparent background. My fix has been to force a light mode stylesheet for napari-matplotlib.

![test_napari_mpl](https://github.com/matplotlib/napari-matplotlib/assets/9143392/411f4c01-85d1-4866-9f82-e1052a41ce36)

Here napari matplotlib is at the top, correctly detecting style as intended (from reading the code).

![napari-window](https://github.com/matplotlib/napari-matplotlib/assets/9143392/41a7d3cc-5caa-4f57-a1d8-6c6249f9dca0)

I don't believe there's any real fix for this, unless a separate savefig was added to `BaseNapariMPLWidget` that overrides the `tickcolor` etc before saving.

**Comment by samcunliffe** [comment]
Ah right, yes.
You will indeed get white lines and ticks with a transparent background if you save straight from the dark mode style.

We put in a way to have [custom stylesheet treated at highest precedence](https://napari-matplotlib.github.io/user_guide.html#customising-plots), if that's any use (perhaps you already found this).
