### ISSUE TITLE
Wouldn't it be handy to extract figure colors directly from the napari theme?

### ISSUE THREAD

**Issue by Chris-N-K** [matplotlib/napari-matplotlib#236]
Thanks for your work :)

What would you think about using the colours provided by the napari theme itself instead of a static style sheet?
Dynamically pulling the colours for the figure parts from the current napari viewer theme, would add support for every style sheet an user could generates for napari.

A possible way to do this would be to extract the theme dict from the viewer: `napari.utils.theme.get_theme(napari.current_viewer.theme, as_dict=True)` and map the colours of interest to the corresponding rcParams keys. Afterwards, instead of providing a path to `with matplotlib.style.context ` you could provide the dict with the rcParams keys and the color codes.

If you think this might be a good idea I would be happy to give it a try and make a pull-request.

**Comment by dstansby** [comment]
I didn't know users could style napari! If that's the case, then pulling dynamically from that style would be much better than supporting a custom style sheet in napari-matplotlib, and a PR would be very welcome! 👍

**Comment by Chris-N-K** [comment]
As far as I know you can actually make style plugins ^^

**Comment by Chris-N-K** [comment]
Checked it, you can even do this easily at runtime.

**Comment by Chris-N-K** [comment]
I close this issue as it was added through the pull request #237
