### ISSUE TITLE
Document how `NapariMPLWidget` can be used by other plugins

### ISSUE THREAD

**Issue by dstansby** [matplotlib/napari-matplotlib#24]
`NapariMPLWidget` provides Matplotlib canvas and toolbar as a widget. It should be possible for external plugins to use this to avoid them having to create the canvas/toolbar themselves. How they can do this should be documented.

**Comment by jo-mueller** [comment]
To pick up this discussion here - how would that work? 

One approach for using the canvas within functions for napari would be something like this:

```Python
import NapariMPLWidget 

def some_function(arg1: ImageData, arg2: float, napari_viewer: napari.viewer.Viewer = None) -> ImageData:
  # function does something here
  if napari_viewer is not None:
    widget = NapariMPLWidget()
    # plot something on the widget
    napari_viewer.window.add_dock_widget(widget)
  return result
```

@kevinyamauchi I think the `napari_viewer` argument is passed automatically if a function is exposed to the napari hook implementation...right?

**Comment by kevinyamauchi** [comment]
Hello @jo-mueller!  for the [widget spec](https://napari.org/plugins/contributions.html#contributions-widgets), the viewer gets passed if one of the widget `__init__`  kwargs is either `napari_viewer` or typed as `napari.viewer.Viewer`. When the user 

I think the best pattern for now is if the plugin is a widget plugin and the `NapariMPLWidget` (or one of its subclasses) is added as a widget to the plugins layout. Something like this:


```python
from napari_matplotlib import ScatterWidget

class MyPlugin(QWidget):
    def __init__(self, napari_viewer: napari.viewer.Viewer):
        # set up some widgets
        my_widget = ...

        # set up the plot widget
        plot_widget =  ScatterWidget(napari_viewer)

        self.layout().addWidget(my_widget)
        self.layout().addWidget(plot_widget)

```

**Comment by dstansby** [comment]
Yes, the above comment from @kevinyamauchi  is pretty much what I had in mind. Even though it's possible to use one of the "specialised" widgets, I'm imagining most people will just use `NapariMPLWidget` to get a blank Matplotlib figure. I'm going to try this out this afternoon with another plugin, so will report back on how it goes!

**Comment by jo-mueller** [comment]
I was hoping that a plot plugin could somehow be created "on-the-fly" from a function that is exposed to magicgui. But creating a regular pyqt measurement plugin works, too.
