### ISSUE TITLE
Add contextual GUI hints on using widgets

### ISSUE THREAD

**Issue by dstansby** [matplotlib/napari-matplotlib#27]
Currently the widgets provide no information on what layers need to be selected to use the widget. This should be added as contextual information somewhere inside the widget panel.

**Comment by samcunliffe** [comment]
User story:

1. I open an RGB image and the scatter plot widget.
2. It tells me I need to select two layers.
3. I select the first layer: no change.
4. I select the second layer, and the help text disappears. A scatter plot is filled 🥳.
5. I _unselect_ one layer, the help text reappears.

**Comment by dstansby** [comment]
Sorry, I forgot about this issue when I was doing https://github.com/matplotlib/napari-matplotlib/pull/139, and just realised you're assigned.

I think https://github.com/matplotlib/napari-matplotlib/pull/139 fixes this? I'm more in favour of a static bit of text than text that appears/disappears depending on how many layers are selected.

**Comment by samcunliffe** [comment]
No no all good. I wasn't doing it. And yes: fewer "moving pieces" is probably better.
