### ISSUE TITLE
Plugin doesn't work with napari>=0.5.0

### ISSUE THREAD

**Issue by zoccoler** [matplotlib/napari-matplotlib#287]
Hi all,

I was trying to update some environments with the latest napari version and where this plugin is installed.
However, that is not possible because this plugin currently requires napari<0.5 as stated [here](https://github.com/matplotlib/napari-matplotlib/blob/c70ad73c23a4e1978506eab4caa06bdc577577b8/setup.cfg#L31). Any plans to have it functional with latest napari versions?

**Comment by dstansby** [comment]
I don't have time to add support at the moment, but PRs welcome! https://github.com/matplotlib/napari-matplotlib/pull/274 is my incomplete effort at fixing this, which might be helpful for anyone who wants to pick it up.

**Comment by jni** [comment]
LOL man it is so weird when things coincide, I was literally just popping in to see what the deal was, and I find a whole bunch of folks requesting the same thing at the same time. 😂 

Can we add a pytest.mark.xfail to the test and get on with our lives? 😂 🙏

**Comment by dstansby** [comment]
I'd rather not just ignore the test in case it's a real issue

**Comment by jni** [comment]
Haha sure I just know from experience that many test failures in big upgrades can be essentially spurious. But your point is definitely taken! 😊

**Comment by dstansby** [comment]
Thanks to @samcunliffe for fixing this - I will try and get a new release out in the next few days, and will keep this open as a reminder to me :)

**Comment by dstansby** [comment]
🚢 released!

**Comment by jni** [comment]
Thank you @dstansby and @samcunliffe!!! ❤️ 🙏

**Comment by zoccoler** [comment]
Thank you guys! Great job!
