### ISSUE TITLE
Create a matplotlibrc file

### ISSUE THREAD

**Issue by dstansby** [matplotlib/napari-matplotlib#36]
Currently we set style options using several lines of code:

https://github.com/matplotlib/napari-matplotlib/blob/1ec14d3662b740be1ce6f50e285b36deb3a1dda8/src/napari_matplotlib/base.py#L9-L13

Instead we should put these in [a `matplotlibrc` file](https://matplotlib.org/stable/tutorials/introductory/customizing.html#the-matplotlibrc-file), to reduce lines of code, and make it easier to edit and see what style settings are being set all in one go.

**Comment by kevinyamauchi** [comment]
Hey @dstansby ! Sorry for my ignorance of how matplotlib configs work, but is setting the configs in this manner "global"? One common use case in napari is people launch a viewer from a jupyter notebook and I think we want to make sure that styling changes made in the plot do not affect styling of plots in the notebook.

**Comment by jo-mueller** [comment]
Just tried adding a mplstyle file to the repo but this changes plotting in Jupyterlab as well :/

**Comment by dstansby** [comment]
I think the way to fix that is use the instructions at https://matplotlib.org/stable/tutorials/introductory/customizing.html#temporary-rc-settings to use a context manager inside `napari-matplotlib`.

**Comment by jo-mueller** [comment]
Thanks for the link - would you then add the decorator to every call to the `draw()` function in the derived widget(s)? Sorry, I haven't worked much with more intricate matplotlib designs, neither.

**Comment by dstansby** [comment]
I *think* it would be sufficient to put a context manager around this line:
https://github.com/matplotlib/napari-matplotlib/blob/4b46774244f42b71b3a24a62ccfa72f357610205/src/napari_matplotlib/base.py#L100
and also anywhere a new Axes is created in the non-base widgets.

**Comment by jo-mueller** [comment]
Thanks @dstansby ,

I tried a few things and it seems that the context manager has to go where the axes object is created, for instance here in the Histogram widget:

https://github.com/matplotlib/napari-matplotlib/blob/081d4b63d36fff3c6f6d72f5f8474b5318b6ede5/src/napari_matplotlib/histogram.py#L21

**Comment by jo-mueller** [comment]
Hi @dstansby, I think this was fixed by #65. The point of a rc file was to not have to set the colors of labels/spines/etc one by one but do it globally. Having this in the `set_default_colorscheme` function makes this irrelevant, I believe.

**Comment by dstansby** [comment]
Going to close this, since work ongoing in other issues and PRs covers this.
