### ISSUE TITLE
can not install matplotlib napari plugin

### ISSUE THREAD

**Issue by sophieRAIBAUD** [matplotlib/napari-matplotlib#54]
hello
I am using python 3.7.1
and can not install this very useful plugin
![image](https://user-images.githubusercontent.com/17746001/177588726-f756c05d-21a4-4f62-b280-97e8ce79f18d.png)
thanks for you help !

Sophie

Collecting napari-matplotlib
  Could not find a version that satisfies the requirement napari-matplotlib (from versions: )
No matching distribution found for napari-matplotlib

**Comment by dstansby** [comment]
You'll need Python>=3.8 to install `napari-matplotlib`, since `napari` requires Python>=3.8 too, so if you update Python it should work - do leave a comment if it doesn't!

**Comment by sophieRAIBAUD** [comment]
Aie
I do not have admin right on my machine, do you know if I can upgrade python ?
For the packages it work 
Many many thanks !!
