### ISSUE TITLE
using this plugin with spatial transcriptomic data (from squidpy)

### ISSUE THREAD

**Issue by sophieRAIBAUD** [matplotlib/napari-matplotlib#55]
Hello
This matplotlib pluggin is great but it doesnt seam to work on my spatial transcriptomic data ....
I launched it with squidpy
Many thanks 
Sophie
![image](https://user-images.githubusercontent.com/17746001/177825996-4c6ceb04-5eaf-4db2-a248-ce736cb4c307.png)

**Comment by dstansby** [comment]
It looks like you have a points layer selected on the left - the slice widget will only work with image layers, so if you click the `hires` layer hopefully it works? We should definitely add a helpful messgage in the widget that says to select an `Image` layer though, so thanks for reporting this!

**Comment by sophieRAIBAUD** [comment]
ok thanks !!
I have 2 question then :)

1. this slice seams to work (y axis = 0 ?)
![image](https://user-images.githubusercontent.com/17746001/180793597-be0ddc5f-ba8d-458e-9f7a-e2252a01ca7e.png)
this one is very strange (values of x between 0 and 2...)
![image](https://user-images.githubusercontent.com/17746001/180793960-e1fbf437-6cb8-490a-a2d1-d9cd5200a2ad.png)

2. would you consider to work on spatial transcriptomic data ?
on the pont data I have is a gene whose expression was measured in each dot 

many many thanks !
Sophie

**Comment by dstansby** [comment]
Could you eplain a bit more why the second image is a bit strange? It looks the same as the first image to me.

> would you consider to work on spatial transcriptomic data ?

`napari-matplotlib` is meant to be a very broad and generic package, so it won't include any research area specific features. If there are any generic features you are insterested in adding suggestions would be super welcome!

**Comment by sophieRAIBAUD** [comment]
working on spatial transcriptomic data would be great. There is a plugin for napari by squipy team
what I woul like to have is extraction og genes expression under 1 spot...
![image](https://user-images.githubusercontent.com/17746001/196700714-4bd3a234-3087-4862-a6b1-8c07d7c4fa11.png)

**Comment by dstansby** [comment]
I think this is out of scope for `napari-matplotlib`, as it is designed to have generic tools that can be used on any data types - thanks for opening though!
