### ISSUE TITLE
Make a feature histogram exploration widget

### ISSUE THREAD

**Issue by jo-mueller** [matplotlib/napari-matplotlib#58]
## Feature proposal

Hi @dstansby ,

I created a feature exploration widget in a [different repository](https://github.com/BiAPoL/napari-stress) together with @zoccoler which shows a `Layer.features` in a histogram along with the cumulative density function. I think it would make sense to move it upstream (e.g., here) - what do you think of it?

Here's a small demo of how it looks/works:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/38459088/195613704-76d61917-9e60-4e35-ba46-775cd3e8e1f9.gif)

The plugin is currently inheriting from `HistogramWidget`.

**Comment by dstansby** [comment]
Oooh this looks interesting! Could you post or link to a higher resolution movie of the gif above? I can't make out the text in the plugin.

Do you have a short summary of what extra features the widget would add on top of `HistogramWidget` too? Perhaps we could consider just adding some of that functionality directly to `HistogramWidget`?

**Comment by jo-mueller** [comment]
Thanks for the reply, will make a higher resolution gif as soon as possible.

As for adding the functionality to the Histogram Widget - not sure. The Histogram widget shows actual pixel intensities of an image layer whereas the example above shows features associated with any layer that supports features. Conceptionally I think it's actually closer to the Scatter Widget 🤔

**Comment by jo-mueller** [comment]
@dstansby here's a more high-res screenshot
![Capture](https://user-images.githubusercontent.com/38459088/199294278-a1a3bb3b-b42e-4f31-b3bb-4d385e82eb05.PNG)

The CDF button shows the cumulative density function:
![Capture](https://user-images.githubusercontent.com/38459088/199294501-aa8b2c43-75e8-4e66-b715-89ca93b719f9.PNG)

**Comment by dstansby** [comment]
Thanks for those images - I think this would be a really nice feature to add. It looks like there might be lots of smaller bits here (the image selection, changing the number of bins, adding a CDF, changing the percentiles, exporting as csv) that could be built incrementally on top of the existing histogram widget. I would strongly prefer for these features to be added in as small as possible chunks in individual PRs, which will make it much easier to review. How does that sound?

I don't have time to work or review this now, but in the new year have CZI funding to work on `napari-matplotlib` and I will definitely add this to our todo list 😄

**Comment by jo-mueller** [comment]
Hi @dstansby ,

thanks for the feedback! I agree, it does make sense to build this on top of the existing histogram rather than building several widgets for specific layers. I guess the key thing would be to build the current histogram widget to feed the data  from 

-  image intensity if an `Image` layer is selected
- `layer.features` if any other layer is selected?

**Comment by dstansby** [comment]
👍 sounds good - PRs very welcome! I think the Historgram widget should do `Image` intensity for a grayscale image, are you looking for intensity for an RGB image?

**Comment by jo-mueller** [comment]
Nah, I don't do RGB much, so as long as nobody complains I would leave it at that (material for another PR, I guess)

**Comment by dstansby** [comment]
Thanks for the reminder for this issue! Mirroring the colourmap of the histgoram with the layer colourmap would definitely be a welcome feature 👍

**Comment by jo-mueller** [comment]
Thanks for merging!
