### ISSUE TITLE
Improve styling and accesibility

### ISSUE THREAD

**Issue by dstansby** [matplotlib/napari-matplotlib#70]
- [x] https://github.com/matplotlib/napari-matplotlib/issues/46
- [x] https://github.com/matplotlib/napari-matplotlib/issues/27
- [x] https://github.com/matplotlib/napari-matplotlib/issues/2
- [x] https://github.com/matplotlib/napari-matplotlib/issues/35
- [x] #86

**Comment by samcunliffe** [comment]
🚀
