### ISSUE TITLE
Axes text to show up in the test figure

### ISSUE THREAD

**Issue by ruaridhg** [matplotlib/napari-matplotlib#96]

**Comment by ruaridhg** [comment]
@dstansby for clarification axes text needs to appear in the below example:

![Image](https://github.com/matplotlib/napari-matplotlib/assets/32329546/15f7fa03-cf6c-4812-a18f-32894fef1aaa)

**Comment by dstansby** [comment]
Yep (and the rest of them). Thinking about this, it's probably worth holding off on this until https://github.com/matplotlib/napari-matplotlib/issues/2 has been done, and then it will be much easier because we can define a custom style sheet for the tests.
